var config = require('./config');
var urlConstant;
urlConstant = {
	POPULAR_EVENTLIST_REQUEST	        : 	config.API_HOST_URL+'/populareventlist',
	GENERAL_SETTING_URL					:	config.API_HOST_URL+'/getsetting',
	EVENT_DETAILS_URL					:  	config.API_HOST_URL+'/eventdetails',
	ADD_TO_CART_URL						: 	config.API_HOST_URL+'/addtocart',
	ADD_TO_EXP_CART_URL					:	config.API_HOST_URL+'/addtoexpcart',
	GET_CART_LIST_URL					:	config.API_HOST_URL+'/getcartlist',
	GET_EXP_CART_LIST_URL				: 	config.API_HOST_URL+'/getexpcartlist',
	REMOVE_ITEM_FROM_CART				:  	config.API_HOST_URL+'/deleteitemfrom',
	UPDATE_ITEM_FROM_CART				:	config.API_HOST_URL+'/updateitemcart',
	UPDATE_EXP_ITEM_FROM_CART			:	config.API_HOST_URL+'/updateexpitemcart',
	CHECK_OFFER							:	config.API_HOST_URL+'/checkoffer',
	PRE_BOOKING							:	config.API_HOST_URL+'/prepaymentbooking',
	PRE_EXP_BOOKING						:	config.API_HOST_URL+'/expressbooking',
	REGISTER_API_REQUEST	        	: 	config.API_HOST_URL+'/register',
	LOGIN_API_REQUEST		        	: 	config.API_HOST_URL+'/login',
	GET_DESTINATION_LIST_URL			:   config.API_HOST_URL+'/getdestinationlist',
	GET_BANNER_LIST_URL					:   config.API_HOST_URL+'/getbannerlist',
	GET_ALL_EVENT_LIST_URL				:	config.API_HOST_URL+'/getalleventlist',
	GET_DESTINATION_EXP_LIST_URL		:   config.API_HOST_URL+'/getdestinationexplist',
	GET_LAST_ORADER_LIST				:   config.API_HOST_URL+'/lastorderlist',
	GET_CITY_NAME_URL					:	config.API_HOST_URL+'/getcityname',
	USER_ORDER_LIST_REQUEST				:	config.API_HOST_URL+'/usereventorderlist',
	USER_DETAIL_REQUEST					:	config.API_HOST_URL+'/userdetails',
	USER_UPDATE_API_REQUEST				:	config.API_HOST_URL+'/updateuser',
	USER_ORDER_DETAILS_REQUEST			:	config.API_HOST_URL+'/usereventorderdetails',
	STATE_LIST_REQUEST					:	config.API_HOST_URL+'/getallstate',
	CITY_LIST_REQUEST					:	config.API_HOST_URL+'/getallcity',
	SEARCH_RESULT_REQUEST				:	config.API_HOST_URL+'/searchresult',
	GET_MEMBERSHIP_LIST					:	config.API_HOST_URL+'/membershiplist',
	PRE_MEMBERSHIP_BOOKING				:	config.API_HOST_URL+'/membershipbooking',
	
}
module.exports = urlConstant;
